# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=b'avatars'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=b'', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'android', b'Android Developer'), (b'designer', b'Designer'), (b'java', b'Java Developer'), (b'php', b'PHP Developer'), (b'python', b'Python Developer'), (b'rails', b'Rails Developer'), (b'wordpress', b'Wordpress Developer'), (b'ios', b'iOS Developer')], max_length=52, null=True),
        ),
    ]
