# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:58
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=b'accounts/avatars'),
        ),
    ]
