# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170427_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
