# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:03
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170501_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to=b'avatar_photos/'),
        ),
    ]
