# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170501_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=b'', max_length=40)),
                ('lastname', models.CharField(default=b'', max_length=40)),
                ('bio', models.CharField(blank=True, default=b'', max_length=300)),
                ('avatar', smartfields.fields.ImageField(blank=True, null=True, upload_to=b'avatar_photos/')),
                ('skills', models.CharField(default=b'', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
