# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170501_1831'),
        ('accounts', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(to='projects.Skill'),
        ),
    ]
