# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170501_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'1', b'Android Developer'), (b'2', b'Designer'), (b'3', b'Java Developer'), (b'4', b'PHP Developer'), (b'5', b'Python Developer'), (b'6', b'Rails Developer'), (b'7', b'Wordpress Developer'), (b'8', b'iOS Developer')], max_length=15, null=True),
        ),
    ]
