# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=b'', max_length=50)),
                ('lastname', models.CharField(default=b'', max_length=50)),
                ('bio', models.CharField(default=b'', max_length=140)),
                ('avatar', smartfields.fields.ImageField(blank=True, null=True, upload_to=b'avatar_photos/')),
                ('slug', models.SlugField(unique=True)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'1', b'Android Developer'), (b'2', b'Designer'), (b'3', b'Java Developer'), (b'4', b'PHP Developer'), (b'5', b'Python Developer'), (b'6', b'Rails Developer'), (b'7', b'Wordpress Developer'), (b'8', b'iOS Developer')], default=b'', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='projects.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
