# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='related_skill',
        ),
        migrations.AddField(
            model_name='position',
            name='requirements',
            field=models.TextField(default=b''),
        ),
    ]
