# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
                ('description', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=50)),
                ('description', models.TextField(default=b'')),
                ('time_estimate', models.TextField(default=b'')),
                ('recruited', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[(b'1', b'Android Developer'), (b'2', b'Designer'), (b'3', b'Java Developer'), (b'4', b'PHP Developer'), (b'5', b'Python Developer'), (b'6', b'Rails Developer'), (b'7', b'Wordpress Developer'), (b'8', b'iOS Developer')], default=b'', max_length=8),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='position',
            name='related_skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Skill'),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Position'),
        ),
    ]
