# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170507_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='requirements',
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(default=b''),
        ),
    ]
