# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170501_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[(b'1', b'Android Developer'), (b'2', b'Designer'), (b'3', b'Java Developer'), (b'4', b'PHP Developer'), (b'5', b'Python Developer'), (b'6', b'Rails Developer'), (b'7', b'Wordpress Developer'), (b'8', b'iOS Developer')], default=b'', max_length=8),
        ),
    ]
