# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170503_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.Position'),
        ),
    ]
